-- ==========================================
-- AURA: Supabase PostgreSQL Schema
-- ==========================================

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. USERS TABLE
-- Extends the default Supabase auth.users table
CREATE TABLE public.users (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT,
    avatar_url TEXT,
    xp INTEGER DEFAULT 0,
    level TEXT DEFAULT 'Sprouting',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. HEALTH METRICS
-- Stores AI analysis results (e.g., Skin Analysis, Outfit Vibe)
CREATE TABLE public.health_metrics (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    metric_type TEXT NOT NULL, -- e.g., 'skin_analysis', 'outfit_analysis'
    data JSONB NOT NULL,       -- Stores the structured Gemini Vision output
    analyzed_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. DAILY FEEDS
-- Generated by n8n Cron Jobs + Gemini to serve the daily dashboard
CREATE TABLE public.daily_feeds (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    target_date DATE NOT NULL DEFAULT CURRENT_DATE,
    content JSONB NOT NULL,    -- Stores tips, meal suggestions, focus areas
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. FOCUS SESSIONS
-- Tracks productivity and mindfulness sessions
CREATE TABLE public.focus_sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    focus_type TEXT DEFAULT 'Deep Work', -- e.g., 'Deep Work', 'Meditation', 'Reading'
    start_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    end_time TIMESTAMPTZ,
    duration_minutes INTEGER,
    xp_earned INTEGER DEFAULT 0,
    status TEXT DEFAULT 'in_progress' -- 'in_progress', 'completed', 'cancelled'
);

-- ==========================================
-- ROW LEVEL SECURITY (RLS)
-- ==========================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.health_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_feeds ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.focus_sessions ENABLE ROW LEVEL SECURITY;

-- Basic RLS Policies (Users can only read/write their own data)
CREATE POLICY "Users can view own profile" ON public.users FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.users FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can view own metrics" ON public.health_metrics FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can view own feeds" ON public.daily_feeds FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can manage own focus sessions" ON public.focus_sessions FOR ALL USING (auth.uid() = user_id);

-- Note: n8n will bypass RLS by using the Supabase Service Role Key to insert data securely.
